name: '🩱 PR'
description: '고생하셨어요'
body:
  - type: textarea
    attributes:
      label: 📝 Summary
      description: 어떤 기능을 구현했는지 알려주세요 !
      placeholder: 실제 예시를 들어주면 좋아요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ⛔️ 주의사항
      description: 문제가 될 수 있는 부분을 설명해주세요.
      placeholder: 조금이라도 애매한 부분이 있었다면 적어주세요.
  - type: textarea
    attributes:
      label: 🧞‍♂️ Etc...
      description: 하고싶은 얘기가 있나요 ?
